### PR TITLE
Eliminate warnings.

### PR DESCRIPTION
**Pull request by fisx**
Aiming for 0 warnings so i can enforce it in CI, but I'm a bit nervous about what you guys things about this idea. :)

EDIT: done!  no warning, and warnings are now errors.  If I get this approved, I'll merge it unsquashed, so that it'll be easy to change your mind about any of these in the future.  Happy to remove any commits we can't immediately agree on (I might just move them to separate PRs where they can linger and get discussed a little).

### CODE REVIEW

**Comment by julialongtin** [comment]
so, i'd generally agree, except...
this is a "haskell sucks, so this goal doesn't work" argument.
the warnings like:
```
./Graphics/Slicer/Math/Skeleton/Motorcycles.hs: warning:
    Could not specialise imported function ‘Data.Either.$w$cshowsPrec’
      when specialising ‘Data.Either.$fShowEither_$cshowsPrec’
      when specialising ‘Data.Either.$fShowEither’
    Probable fix: add INLINABLE pragma on ‘Data.Either.$w$cshowsPrec’

./Graphics/Slicer/Math/Skeleton/Motorcycles.hs: warning:
    Could not specialise imported function ‘Data.Either.$fShowEither_$cshow’
      when specialising ‘Data.Either.$fShowEither’
    Probable fix: add INLINABLE pragma on ‘Data.Either.$fShowEither_$cshow’
```
are worth ignoring if it's upstream's code, but are real warnings (and are the compiler saying "hey, let me optimize like i want!") for YOUR code.

this makes this generally not work for me. i WANT those warnings when they're pointing TO my library. i don't want them when they point to code i cannot change.

**Comment by Kleidukos** [comment]
@julialongtin Are those out-of-package warnings going to be caught by -Werror in your package? I thought you had to enable -Werror for the package in question in your cabal.project to get this behaviour.

**Comment by fisx** [comment]
> @julialongtin Are those out-of-package warnings going to be caught by -Werror in your package? I thought you had to enable -Werror for the package in question in your cabal.project to get this behaviour.

Yes, and the evidence is in the CI log: you get the warnings there, but they don't count as errors, everything is green.

**Comment by fisx** [comment]
The possible issue I expected people might have with this is that if you `cabal build` locally, you get errors now where you got warnings before.  I actually prefer to develop with even errors being warnings, and let the CI catch me if I'm missing anything.  I'm sure there is a solution for this, but I'm not sure what it is.

**Comment by julialongtin** [comment]
Yeah. historically, i tried to run this project with -werror in the flags, but it was costing me users.

**Comment by Kleidukos** [comment]
@julialongtin If you want to only enable -Werror during CI, you can do like this: https://github.com/divarvel/biscuit-haskell/commit/d3a2dec60fddccab3aaac034435571f000557eb3

**Comment by fisx** [comment]
Happy to do that.  And if you want to not do it, I'll take that commit back.  Your call!

**Comment by julialongtin** [comment]
@Kleidukos great implementation.
@fisx let's do that. :)

**Comment by fisx** [comment]
Oh, I just realized it's more complicated for us, since we're generating `ci.yaml` from https://github.com/sorki/github-actions-dhall/blob/pending/haskell-ci.dhall.

I'll think of something, but I'll do it in another PR.  This one would be ready to merge, then.

**Comment by fisx** [comment]
*now* it's ready for final review (and please merge if you approve).

**Review by julialongtin — APPROVED** [review]

**Comment by julialongtin** [comment]
Great work, and thanks everyone! :)

**Pull request merged**
